#!/usr/bin/env bash
# Copy the shared frontend modules from lamsza (the owner) into lamsza-admin,
# then regenerate the hash manifest in both repos.
#
# The decision behind this script is docs/network/SHARED_FRONTEND_MODULES.md.
# Short version: lamsza owns these files, lamsza-admin gets a generated copy,
# and each repo's own test suite hashes its own copies against the manifest, so
# drift is a red build in whichever repo drifted - with only that repo checked
# out.
#
# Usage:
#   scripts/sync-shared-frontend.sh            # copy + rewrite both manifests
#   scripts/sync-shared-frontend.sh --check    # verify only, change nothing
#
# LAMSZA_ADMIN_ROOT overrides where lamsza-admin lives (default ../lamsza-admin
# next to this repo).

set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
admin=${LAMSZA_ADMIN_ROOT:-$(cd "$here/.." && pwd)/lamsza-admin}
manifest="$here/shared-frontend-modules.json"
admin_manifest="$admin/frontend/shared-frontend-modules.json"
check_only=0
[ "${1:-}" = "--check" ] && check_only=1

if [ ! -f "$manifest" ]; then
  echo "missing $manifest" >&2
  exit 1
fi
if [ ! -d "$admin/frontend/src" ]; then
  echo "lamsza-admin frontend not found at $admin/frontend - set LAMSZA_ADMIN_ROOT" >&2
  exit 1
fi

# The manifest's own key order is the module list.
modules=$(node -e '
  const m = require(process.argv[1]);
  console.log(Object.keys(m.modules).join("\n"));
' "$manifest")

fail=0
for path in $modules; do
  src="$here/$path"
  dst="$admin/frontend/$path"
  if [ ! -f "$src" ]; then
    echo "MISSING in lamsza: $path" >&2
    fail=1
    continue
  fi
  if [ "$check_only" = 1 ]; then
    if ! cmp -s "$src" "$dst"; then
      echo "DRIFT: $path differs between lamsza and lamsza-admin" >&2
      fail=1
    fi
    continue
  fi
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
done

if [ "$check_only" = 1 ]; then
  [ "$fail" = 0 ] && echo "shared frontend modules: in step"
  exit "$fail"
fi
[ "$fail" = 0 ] || exit 1

tmp=$(mktemp)
{
  echo '{'
  echo '  "_": "Generated by lamsza/scripts/sync-shared-frontend.sh. Do not hand-edit the hashes.",'
  echo '  "owner": "waaab/lamsza",'
  echo '  "consumer": "waaab/lamsza-admin (frontend/ prefix)",'
  echo '  "doc": "docs/network/SHARED_FRONTEND_MODULES.md",'
  echo '  "modules": {'
  first=1
  for path in $modules; do
    sum=$(sha256sum "$here/$path" | cut -d' ' -f1)
    [ "$first" = 1 ] || echo ','
    first=0
    printf '    "%s": "sha256:%s"' "$path" "$sum"
  done
  echo
  echo '  }'
  echo '}'
} > "$tmp"

mv "$tmp" "$manifest"
cp "$manifest" "$admin_manifest"
echo "synced $(echo "$modules" | wc -l | tr -d ' ') shared modules into $admin/frontend"
echo "manifests rewritten: $manifest"
echo "                     $admin_manifest"
echo "Commit both repos."
