name: Build and Test Lamsza

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Svelte frontend
        run: npm install && npm run build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.7'
          cache-dependency-path: backend/go.sum

      - name: Build Go backend
        run: cd backend && go build -o sz-gugel-bin main.go
